<?php

namespace Container0b9Ghe7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorySearchTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CategorySearchType' shared autowired service.
     *
     * @return \App\Form\CategorySearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CategorySearchType.php';

        return $container->privates['App\\Form\\CategorySearchType'] = new \App\Form\CategorySearchType();
    }
}
